[dev] organize ctl

diff --git a/launch b/launch
--- a/launch
+++ b/launch
@@ -1,6 +1,9 @@
 #!/bin/bash
 set -eou pipefail
 
+ctl_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
+root_dir="$(cd "$(dirname "$ctl_dir")" && pwd)"
+
 CYAN='\033[0;36m'
 GREEN='\033[0;32m'
 RED='\033[0;31m'
@@ -35,20 +38,17 @@ done
 shift $((OPTIND-1))
 
 project="${1:-}"
-msg_aux=""
+ctl_title="[ctl]"
 
 if [ "${dev:-}" = "true" ]; then
-	msg_aux=" [dev mode]"
+	ctl_title=" [ctl - dev mode]"
 fi
 
 start="$(date '+%F %T')"
-echo -e "${CYAN}$start [start]$msg_aux running the project ($project)${NC}"
-
-ctl_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
-root_dir="$(cd "$(dirname "$ctl_dir")" && pwd)"
+echo -e "${CYAN}$start $ctl_title [start] running the project ($project)${NC}"
 
 if [ -z "$project" ]; then
-	echo "[error] enter the project name"
+	echo "[error] $ctl_title enter the project name"
 	exit 2
 fi
 
@@ -96,7 +96,7 @@ if [ "$var_container_type" = "" ]; then
 fi
 
 if [ "$var_container_type" != 'docker' ]; then
-    echo "[error] unsupported container type: $var_container_type"
+    echo "[error] $ctl_title unsupported container type: $var_container_type"
     exit 2
 fi
 
@@ -107,7 +107,7 @@ if [ "$var_root" = 'true' ]; then
 fi
 
 if [ "${fast:-}" = 'true' ]; then
-	echo "[ctl] skipping init project (fast)..."
+	echo "$ctl_title skipping init project (fast)..."
 else
     prepare_args=()
 
@@ -130,15 +130,15 @@ else
 		--extra-vars "env_project_key=$project" \
 		--extra-vars "env_root_dir=$root_dir" \
 		--extra-vars "env_dev=${dev:-}" \
-		init.yml \
-		|| error "[error] project $project - init"
+		main.yml \
+		|| error "[error] $ctl_title project $project - init"
 fi
 
 bash "${root_dir}/projects/$project/files/ctl/run" \
 	${args[@]+"${args[@]}"} "${@}" \
-	|| error "[error] project $project - run"
+	|| error "[error] $ctl_title project $project - run"
 
 end="$(date '+%F %T')"
-echo -e "${CYAN}$end [end]$msg_aux running the project ($project)${NC}"
+echo -e "${CYAN}$end $ctl_title [end] running the project ($project)${NC}"
 
-echo -e "${GREEN} [project - $project] [run$msg_aux] summary - $start to $end ${NC}"
+echo -e "${GREEN} $ctl_title [project - $project] [run] summary - $start to $end ${NC}"
