[dev] subuser

diff --git a/launch b/launch
--- a/launch
+++ b/launch
@@ -153,10 +153,13 @@ else
 			sudo groupadd -f "$var_main_user_group" || error "[error] create main user group"
 			sudo usermod -a -G "$var_main_user_group" "$main_user" || error "[error] add main user to group"
 
+			subuser_home_dir="${root_dir}/projects/$project/$subuser"
+
 			sudo groupadd -f "$var_subuser_group" || error "[error] create subuser group"
-			id -u somename &>/dev/null \
-				|| sudo useradd --no-create-home --shell /bin/bash "$subuser" \
+			id -u "$subuser" &>/dev/null \
+				|| sudo useradd "$subuser" --create-home  --home-dir "$subuser_home_dir" --shell /bin/bash \
 				|| error "[error] create subuser"
+			sudo chown "$subuser":"$subuser" "$subuser_home_dir"
 			sudo passwd -l "$subuser" || error "[error] disable subuser login"
 			sudo usermod -a -G "$var_subuser_group" "$subuser" || error "[error] add subuser to group"
 		fi
@@ -193,17 +196,17 @@ else
 fi
 
 if [ "${enter:-}" != 'true' ]; then
-	cmd=( bash )
+	cmd=( bash "${root_dir}/projects/$project/files/ctl/run" ${args[@]+"${args[@]}"} "${@}" )
+	error_msg="[error] $ctl_title project $project - run"
 
-	if [ -n "$var_subuser_group" ]; then
-		cmd=( sudo su - "$subuser" bash )
-		"${cmd[@]}" "whoami=$(whoami)"
-		exit 0
+	if [ -z "$var_subuser_group" ]; then
+		"${cmd[@]}" || error "$error_msg (same user)"
+	else
+		sudo su - "$subuser" bash || error "$error_msg (as $subuser)" <<-SHELL
+			set -eou pipefail
+			${cmd[@]}
+		SHELL
 	fi
-
-	"${cmd[@]}" "${root_dir}/projects/$project/files/ctl/run" \
-		${args[@]+"${args[@]}"} "${@}" \
-		|| error "[error] $ctl_title project $project - run"
 fi
 
 end="$(date '+%F %T')"
