[dev] container args

diff --git a/ansible/run b/ansible/run
--- a/ansible/run
+++ b/ansible/run
@@ -1,6 +1,17 @@
 #!/bin/bash
 set -eou pipefail
 
+trap 'echo "[error] ${BASH_SOURCE[0]}:$LINENO" >&2; exit 3;' ERR
+
+RED='\033[0;31m'
+NC='\033[0m' # No Color
+
+function error {
+	msg="$(date '+%F %T') - ${BASH_SOURCE[0]}:${BASH_LINENO[0]}: ${*}"
+	>&2 echo -e "${RED}${msg}${NC}"
+	exit 2
+}
+
 dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
 project_dir="$(cd "$dir/../.." && pwd)"
 root_dir="$(cd "$project_dir/../../.." && pwd)"
@@ -13,18 +24,11 @@ var_dev="$dev"
 var_container="$container"
 var_container_type="$container_type"
 var_allow_container_type="$allow_container_type"
+var_container_network="$container_network"
+var_container_opts="$container_opts"
 var_root="$root"
 var_run_file="$run_file"
 var_force_vault="$force_vault"
-
-RED='\033[0;31m'
-NC='\033[0m' # No Color
-
-function error {
-	msg="$(date '+%F %T') - ${BASH_SOURCE[0]}: line ${BASH_LINENO[0]}: ${*}"
-	>&2 echo -e "${RED}${msg}${NC}"
-	exit 2
-}
 
 last_index=1
 
@@ -88,14 +92,25 @@ fi
 if [ "${inside:-}" = 'true' ]; then
     "${inner_cmd[@]}" || error "[error] project run - init (inside)"
 else
-	name_cmd=()
+	cmd_args=()
 
 	if [ "${multiple:-}" != 'true' ]; then
-		name_cmd=( --name="local-ctl-$project" )
+		cmd_args+=( --name="local-ctl-$project" )
+	fi
+
+	if [ -n "$var_container_network" ]; then
+		"${cmd[@]}" network inspect "$var_container_network" >/dev/null 2>&1 || \
+			"${cmd[@]}" network create --driver bridge "$var_container_network"
+		cmd_args+=( --network "$var_container_network" )
+	fi
+
+	if [ -n "$var_container_opts" ]; then
+		mapfile -td ' ' var_container_args < <(printf '%s' "${var_container_opts:-}")
+		cmd_args+=( ${var_container_args[@]+"${var_container_args[@]}"} )
 	fi
 
 	"${cmd[@]}" run --rm -it \
-		${name_cmd[@]+"${name_cmd[@]}"} \
+		${cmd_args[@]+"${cmd_args[@]}"} \
 		--workdir='/main' \
 		-e "FORCE_VAULT=$var_force_vault" \
 		"${volumes[@]}" \
diff --git a/launch b/launch
--- a/launch
+++ b/launch
@@ -1,6 +1,8 @@
 #!/bin/bash
 set -eou pipefail
 
+trap 'echo "[error] ${BASH_SOURCE[0]}:$LINENO" >&2; exit 3;' ERR
+
 ctl_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
 root_dir="$(cd "$(dirname "$ctl_dir")" && pwd)"
 
@@ -10,7 +12,7 @@ RED='\033[0;31m'
 NC='\033[0m' # No Color
 
 function error {
-	msg="$(date '+%F %T') - ${BASH_SOURCE[0]}: line ${BASH_LINENO[0]}: ${*}"
+	msg="$(date '+%F %T') - ${BASH_SOURCE[0]}:${BASH_LINENO[0]}: ${*}"
 	>&2 echo -e "${RED}${msg}${NC}"
 	exit 2
 }
@@ -119,6 +121,8 @@ else
 	var_container="$container"
 	var_container_type="${container_type:-}"
 	var_allow_container_type="${allow_container_type:-}"
+	var_container_network="${container_network:-}"
+	var_container_opts="${container_opts:-}"
 	var_root="${root:-}"
 	var_use_subuser="${use_subuser:-}"
 	var_subuser_prefix="${subuser_prefix:-}"
@@ -283,15 +287,26 @@ else
 					main_env_dir="$(readlink -f "$main_env_dir")"
 				fi
 
-				name_cmd=()
+				cmd_args=()
 
 				if [ "${multiple:-}" != 'true' ]; then
-					name_cmd=( --name="local-ctl-$project" )
+					cmd_args+=( --name="local-ctl-$project" )
+				fi
+
+				if [ -n "$var_container_network" ]; then
+					"${container_cmd[@]}" network inspect "$var_container_network" >/dev/null 2>&1 || \
+						"${container_cmd[@]}" network create --driver bridge "$var_container_network"
+					cmd_args+=( --network "$var_container_network" )
+				fi
+
+				if [ -n "$var_container_opts" ]; then
+					mapfile -td ' ' var_container_args < <(printf '%s' "${var_container_opts:-}")
+					cmd_args+=( ${var_container_args[@]+"${var_container_args[@]}"} )
 				fi
 
 				cmd=( \
 					"${container_cmd[@]}" run --rm -it \
-						${name_cmd[@]+"${name_cmd[@]}"} \
+						${cmd_args[@]+"${cmd_args[@]}"} \
 						--workdir "/main/ctl" \
 						-v "${ctl_dir}:/main/ctl:ro" \
 						-v "${main_env_dir}:/main/ctl/env-main:ro" \
diff --git a/run b/run
--- a/run
+++ b/run
@@ -1,6 +1,8 @@
 #!/bin/bash
 set -eou pipefail
 
+trap 'echo "[error] ${BASH_SOURCE[0]}:$LINENO" >&2; exit 3;' ERR
+
 ctl_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
 main_env_dir="${ctl_dir:?}/env-main"
 
@@ -13,7 +15,7 @@ RED='\033[0;31m'
 NC='\033[0m' # No Color
 
 function error {
-	msg="$(date '+%F %T') - ${BASH_SOURCE[0]}: line ${BASH_LINENO[0]}: ${*}"
+	msg="$(date '+%F %T') - ${BASH_SOURCE[0]}:${BASH_LINENO[0]}: ${*}"
 	>&2 echo -e "${RED}${msg}${NC}"
 	exit 2
 }
@@ -101,9 +103,11 @@ case "$command" in
 		var_container="$container"
 		var_container_type="${container_type:-}"
 		var_allow_container_type="${allow_container_type:-}"
+		var_container_network="${container_network:-}"
+		var_container_opts="${container_opts:-}"
 		var_root="${root:-}"
 
-		if [ "$var_container_type" = "" ]; then
+		if [ -z "$var_container_type" ]; then
 			var_container_type="docker"
 		fi
 
@@ -119,12 +123,26 @@ case "$command" in
 			cmd=( sudo "$var_container_type" )
 		fi
 
+		cmd_args=()
+
+		if [ -n "$var_container_network" ]; then
+			"${cmd[@]}" network inspect "$var_container_network" >/dev/null 2>&1 || \
+    			"${cmd[@]}" network create --driver bridge "$var_container_network"
+			cmd_args+=( --network "$var_container_network" )
+		fi
+
+		if [ -n "$var_container_opts" ]; then
+			mapfile -td ' ' var_container_args < <(printf '%s' "${var_container_opts:-}")
+			cmd_args+=( ${var_container_args[@]+"${var_container_args[@]}"} )
+		fi
+
 		"${cmd[@]}" run --rm -it \
 			--name="local-ctl-init" \
 			--workdir="/main/tmp" \
 			-v "${ctl_dir}/tmp:/main/tmp" \
 			-e "UID=$(id -u)" \
 			-e "GID=$(id -g)" \
+			${cmd_args[@]+"${cmd_args[@]}"}
 			"$var_container" \
 			|| error "[error] $command"
 		;;
